language: python
python:
    - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/

before_install:
    - export TZ=America/Denver
install:
    - pip install codecov
    - pip install pylint
    - pip install .
    - pip install -r requirements.txt --cache-dir $HOME/.pip-cache --only-binary pandas

script:
    - coverage run testAll.py
    - pylint --errors-only  omniture/.
after_success:
     bash <(curl -s https://codecov.io/bash)
     codecov
